language: node_js

node_js:
    - 'node'
    - 13
    - 12
    - 11
    - 10
    - 9
    - 8

branches:
    only:
        - master
        - /^release-.*/

install:
    - npm install

cache:
    directories:
        - node_modules

before_script:
    - npm run setup
    - npm run build

scripts:
    - npm test
#   - npm run coverage

# after_success:
#   - npm pack
