language: node_js

node_js:
  - 'node'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'

branches:
  only:
  - master
  - /^release-.*/

install:
  - npm install

cache:
  directories:
    - node_modules

before_script:
  - npm run setup
  - npm run build

scripts:
  - npm test
#   - npm run coveralls

after_success:
  - npm pack
