name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    strategy:
      matrix:
        node-version: [10.x, 12.x]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    docker:
      - image: circleci/node:1.1.6
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        steps:
        - run: npm install
        - run: npm rename
        - run: npm run build
        - run: npm test
      env:
        CI: true

workflows:
  version: 2
    build-and-test:
      jobs:
        - build-and-test
